### ISSUE TITLE
Checked and unchecked state are the same for QRadioButton and QCheckBox in Qt application.

### ISSUE THREAD

**Issue by karakozov** [pgilfernandez/FreeCAD_Blender-stylesheet#3]
Hi!
Thank you for your project! I try to use your styles in my Qt application, and have some issues with view of QRadioButton, QCheckBox in checked and unchecked state. I try to fix it by myself, but 
don't have great experience in Qt. Can you help me, please? 
Windows 10 x86_64, Qt 5.14.2, MingW 7.3.0 (from Qt) 
Free CAD 0.18

![image-view](https://user-images.githubusercontent.com/4922062/80836885-5c9d7b00-8bfe-11ea-83c4-b3354c6618b9.PNG)

Thank you.

**Comment by luzpaz** [comment]
@pgilfernandez ping

**Comment by pgilfernandez** [comment]
Thanks for the ping @luzpaz, I missed the original issue.

Hi @karakozov,
I think your problem is related with the paths to the images files that are used in the ON states of those checkboxes and Radiobuttons.

At the start of the .qss file you can find useful information, read it and you may learn new things. About this issue, at the installation chapter it says:
```
...Images used in the theme need ABSOLUTE paths to be found by FreeCAD, so you should search the string "qss:images" (without "") and replace with the real path of your computer. It should be done with all the .qss files you want to install-use
        find = qss:images
        replace = /Users/myName/Library/Preferences/FreeCAD/Gui/Stylesheets/images
```

For instance we can follow the QRadioButton example, in my original .qss file it reads:
```
QRadioButton::indicator:checked {
    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #373737, stop:1 #535353);
    border: 1px solid #292929; /* QCheckBox has the same color */
    image:url(qss:images_dark-light/radiobutton_light.svg);
}
```
The line with the `image` parameter should point to the absolute path of the file, something like (under Windows as it seems this is the OS you run):
```
QRadioButton::indicator:checked {
    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #373737, stop:1 #535353);
    border: 1px solid #292929; /* QCheckBox has the same color */
    image:url(C:/[INSTALLATION_PATH_OF_IMAGE_FILES_OF_THIS_STYLESHEET]/radiobutton_light.svg);
}
```
Finally, if this doesn't work, the problem could be related with your Qt app not rendering SVG files on the go as FreeCAD does. Try investigating this as I don't know about coding Qt... but, before trying to implement SVG rendering, an easy workaround would be to use PNG files instead. I mean, if you convert all SVG files with Inkscape or ImageMagick (or similar) to PNG and use the same filenames you just need to use absolute paths to the images files and find/replace all ".svg" to ".png".

I hope I gave you enough clues to close your issue... let me know.
Cheers

**Comment by karakozov** [comment]
Thank you for your answer!
